# Generated by Django 4.1.5 on 2023-01-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_rename_desease_update_animal_info_desease_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_info',
            name='desease_description',
        ),
    ]
