# Generated by Django 4.1.5 on 2023-01-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_remove_animal_info_desease_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_info',
            name='desease_update',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
